# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(default='', max_length=100, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='contact',
            name='remark',
            field=models.CharField(default='', max_length=100, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social',
            field=models.CharField(default='', max_length=100, verbose_name='social'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='phone'),
        ),
    ]
