# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20151213_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='emailType',
            field=models.CharField(default='', max_length=100, verbose_name='emailType'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phoneType',
            field=models.CharField(default='', max_length=100, verbose_name='phoneType'),
        ),
        migrations.AddField(
            model_name='contact',
            name='socialType',
            field=models.CharField(default='', max_length=100, verbose_name='socialType'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
    ]
